import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';

import './globals.css';

import { ModalProvider } from '@/providers/modalProvider';
import { ToastProvider } from '@/providers/toastProvider';
import { ThemeProvider } from '@/providers/themeProvider';

const font = Roboto_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={font.className}>
          <ToastProvider />
          <ModalProvider />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
